### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by hbh3** [ElvishArtisan/GlassCoder#10]
My installation of GlassCoder was previously working to a local Icecast2 server fine, but when I switched to a remote server, I am getting the below error.  Any idea what is causing the extra //stream on the end?

`# glasscoder --server-type=icecast2 --server-url=http://radio.streamer.com:xxxx/stream --server-auth=user:password --verbose --audio-format=mp3 --audio-samplerate=48000 --audio-channels=2 --audio-bitrate=128 --stream-name="streamname" --stream-description="streamdesc" --stream-url="https://listen.mydomain.com" --stream-genre="80s" --audio-device=jack --jack-server-name="rivendell_0" --jack-client-name="MainLog" --jack-gain=0

glasscoder: connected to JACK graph at 48000 samples/sec.

glasscoder: connection to "http://radio.streamer.com:xxxx/stream//stream" lost`

**Comment by newdanceradio** [comment]
I have the same issue, exactly the same error
glasscoder: connection to "http://stream.newdanceradio.ru/mp3_192_fallback//mp3_192_fallback"  lost
And yes, if the icecast server is working in local everything is fine, but if server is at remote location, everytime got the same error, and what is interesting, that glasscoder is showing that it's reconnecting, but really it isn't.

**Comment by ElvishArtisan** [comment]
Both of these are indicative of a network problem. The 'reconnecting' message means just that -- glasscoder(1) is attempting to reconnect. In this case, clearly unsuccessfully.

One good way to test network connectivity is to use telnet(1). You should be able to do:

```telnet <server-ip> <server-port>```

and get a connection. ITOH, if the command hangs, or throws an error message, you have a network problem.

N.B. That telnet command takes a *space* between the address and port arguments, **not** a ':'.

**Comment by hbh3** [comment]
Thanks for replying.

I get through with telnet and I get a connection:

telnet 123.123.123.123 1234
Trying 112.123.123.123...
Connected to 123.123.123.123.
Escape character is '^]'.

Darkice and BUTT are working on my configuration but not GlassCoder.  I even have BUTT working with SSL so I know both the unencrypted and the SSL ports at my host are working with other software.  I prefer to use GlassCoder.

**Comment by ElvishArtisan** [comment]
Should be fixed in 31807fa. Please test!

**Comment by starrbuck68** [comment]
This makes me very happy!  Compiling now and preparing to test.

**Comment by starrbuck68** [comment]
Make issue:

In file included from hlsconnector.h:52:0,
                 from connectorfactory.cpp:23:
fileconveyor.h:27:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>

**Comment by hbh3** [comment]
This makes me very happy!  Compiling now and preparing to test.

**Comment by hbh3** [comment]
Ran into a make issue:

In file included from hlsconnector.h:52:0,
                 from connectorfactory.cpp:23:
fileconveyor.h:27:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>

**Comment by hbh3** [comment]
I fixed this by installing libcurl-devel package.

**Comment by hbh3** [comment]
Confirmed fixed!

Worked fine for http connection to the Icecast2 server but did not work for https connection (similar error as originally reported with the double "stream//stream" being sent). Should it work with https connections as well? I'm happy with http for now.

Thank you!

**Comment by ElvishArtisan** [comment]
> In file included from hlsconnector.h:52:0,
from connectorfactory.cpp:23:
fileconveyor.h:27:23: fatal error: curl/curl.h: No such file or directory
#include <curl/curl.h>

Interesting. That should have been caught by the configure script!

**Comment by ElvishArtisan** [comment]
> Confirmed fixed!

Cool. Thank you for testing!

> Worked fine for http connection to the Icecast2 server but did not work for https connection (similar error as originally reported with the double "stream//stream" being sent). Should it work with https connections as well? I'm happy with http for now.

HTTPS is not supported (yet). That will be a whole kettle of fish in its own right, especially as Icecast support for HTTPS has itself only recently stabilized.

**Comment by ElvishArtisan** [comment]
> In file included from hlsconnector.h:52:0,
from connectorfactory.cpp:23:
fileconveyor.h:27:23: fatal error: curl/curl.h: No such file or directory
#include <curl/curl.h>

Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 8fdd494.
