### ISSUE TITLE
Missing release tarball for May/2021 debianish-frindly changes.

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/GlassCoder#12]
Hi!

I've been re-checking this repo and I have relized that the May 2021 commits did, in fact, paved the way to build Debian packages.... I've tested on both Debian Buster and Bullseye, and in both cases, the packages can build out-of-the box... THANK YOU!

Now but, I miss having such (IMHO) important changes packed as a release tarball, so we could now build .deb packages based on an official release, out of the source-tree.

Anyways... thank you so much!

**Comment by ElvishArtisan** [comment]
I believe GlassCoder may already be packaged for Debian. See #8.

**Comment by alexolivan** [comment]
Hey! ... I'm missing something as always (noooooob).... I'm using your release tarballs as a way to create 'release' debian packages, not git (which I use to create bleeding-edge, 'snapshot' packages)

So, the last tarball I find is https://github.com/ElvishArtisan/GlassCoder/releases/download/v1.0.1/glasscoder-1.0.1.tar.gz dating from June 23, 2020 ... isn'it? or Am I missing an updated release tarball anywhere?

Best regards.

**Comment by ElvishArtisan** [comment]
Released as v1.0.2.

**Comment by alexolivan** [comment]
Thank you very much.
Now I got this packaged as a release version :-) .... I don't understand why the packages do build as 1.0.1 while I see you updated  DPKG version to 1.0.2. Maybe something in my environment but I don't understand why that happens. 
The application but, to the extend I have tested, works as expected! :-)
