### ISSUE TITLE
Use dlopen for more optional libraries

### ISSUE THREAD

**Issue by cbix** [ElvishArtisan/GlassCoder#15]
Some linked libraries [are already being](https://github.com/ElvishArtisan/GlassCoder/search?q=dlopen) `dlopen`ed (like `libfdk-aac`, `libvorbis` and other codecs) and gracefully ignored if not present, allowing optional features to be compiled into the binary. This is not yet the case for other libraries, mostly the audio source libs:
- libjack
- libasound
- libsndfile
- libhpi
- and potentially more?

Currently, launching glasscoder without all of these present, I'd get errors like
```
glasscoder: error while loading shared libraries: libhpi.so.10: cannot open shared object file: No such file or directory
```
with the software not starting at all.

When packaging for a linux distribution, it would be nice to compile in support for all of these, but let the user choose what they need. For example, if running on a machine without sound support and I only wanted to stream from audio files, I wouldn't need to have ALSA and JACK libs installed.

**Comment by ElvishArtisan** [comment]
I agree that it would be nice, but using ```dlopen()``` incurs a significant cost in terms of code complexity. We've elected to pay those costs in the case of the codecs because those libraries are notoriously prone to patent encumbrances, and thus various users need to be able to opt in or out in accordance with the various IP regimes under which they operate. The benefits of the tradeoff in the case of the audio source libraries is much less clear-cut; limited mostly to a modest savings in memory and storage utilization. I don't see that as being a compelling case at the moment.

**Comment by cbix** [comment]
I see, that's a totally valid reason :) Maybe [weakjack](https://github.com/x42/weakjack) helps with this at least for JACK, but I see the whole application would have to deal with JACK not being available, i.e. hiding the option in the GUI etc. and that may not be worth the effort for you.

**Comment by ElvishArtisan** [comment]
> Maybe [weakjack](https://github.com/x42/weakjack) helps with this at least for JACK

Interesting project, I had not seen this before. Thanks for the link! It does have problems with Windows compatibility though, specifically under Mingw. Overall, I'm not sure that the net global complexity would be significantly reduced, while introducing an additional (and perhaps somewhat exotic) dependency.

**Comment by cbix** [comment]
I haven't used weakjack myself yet, either, but claims to be sort of a drop-in solution and could simply be vendored by glasscoder. Zrythm for example simply [includes it in their codebase](https://github.com/zrythm/zrythm/tree/master/ext/weakjack).

**Comment by ElvishArtisan** [comment]
Ah, I see; the idea is that a project simply 'swallow' the code. That eliminates the dependency aspect. Thanks for pointing that out!
