### ISSUE TITLE
Version number in release title?

### ISSUE THREAD

**Issue by mxmilkiib** [ElvishArtisan/GlassCoder#16]
Hi, I'd like to add GlassCoder to https://libreav.org which has a release aggregation feature, but there's no version numbers in the releases.atom entry titles. Might it be possible to prefix or suffix the text "Production Release" with a number, like "1.0.4 - Production Release"?

**Comment by ElvishArtisan** [comment]
Interesting -- this is the first time I've heard of this particular GitHub feature. Unfortunately, I'm having difficulty discovering much about it; searches on "release.atom" at https://help.github.com return zero results, while googling the phrase returns mostly a bunch of stuff about the Atom HTML editor that GibHub maintains. Might you have some pointers to some useful documentation?

In the meantime, FWIW, GlassCoder uses [Semantic Versioning](https://semver.org); with each release being tagged with its version string prepended with a 'v'. Test releases are rather infrequent, but get explicitly marked as 'pre-release' in the release metadata.

**Comment by mxmilkiib** [comment]
https://vilcins.medium.com/rss-feeds-for-your-github-releases-tags-and-activity-cbda2c51373 has more info. Semantic version numbers including a v works also be welcome (the regex I use can filter those)! If there's no number the feed entry is ignored.

**Comment by ElvishArtisan** [comment]
Thanks. That's a start.

So, the DTD identifies that as a standard Atom feed. I see the release versions in the &lt;title&gt; field of each entry. Is that what you're looking for?

**Comment by mxmilkiib** [comment]
Ah I missed the fact there are entries for tags in the feed! Strange though, I'm only seeing some of the entries through my system, I need to investigate the regex I'm using, I certainly didn't think it was that broken, too tired to investigate right now;
![image](https://user-images.githubusercontent.com/108225/175795403-5f5eaaa6-13ff-4d7a-a095-cd7fb259c6ab.png)
Though when I look at the feed with [feed preview](https://code.guido-berhoerster.org/addons/firefox-addons/feed-preview/), I see
![image](https://user-images.githubusercontent.com/108225/175795432-2893d835-9aaa-43ed-bd01-3cb10f738922.png)

**Comment by mxmilkiib** [comment]
I'm mindful now that if a tag is used as a release, that default tag entry doesn't appear in the releases.atom, instead it appears as a release entry with the new title. Unfortunately the Drupal Feeds system currently cannot do conditional filtering when reading/manipulating entry field content, so it's not possible to use the entry id element, which does include the original tag name, because sites other than GitHub don't use this convention so there's no way to map from one of two entries depending on their content.

**Comment by ElvishArtisan** [comment]
Looping back on this (now rather old) issue. Were you able to get this working? I confess that the discussion of the Drupal Feeds System is way over my head.
