### ISSUE TITLE
Shoutcast Stream Port

### ISSUE THREAD

**Issue by PeWe79** [ElvishArtisan/GlassCoder#21]
I don't know why if stream with Shoutcast server, PORT must be reduce (- / minus) one. For example if server actualy on 192.168.1.100:800 must be on 192.168.1.100:799
If not reduce one Glasscommander or GlassGui failed to connect to server.

**Comment by ElvishArtisan** [comment]
The Shoutcast protocol actually allocates _two_ ports for each audio "stream"; one for the actual streaming data and another (one port higher) for the metadata interface. The convention seems to be to use the streaming data port number as "the number", but who knows? None of this internal info is publicly documented by Shoutcast.

What version of Shoutcast were you seeing this behavior with?

**Comment by PeWe79** [comment]
Hi @ElvishArtisan Thanks. I use Shoutcast Server v2.6.1.777/posix(linux x64).
No other issue except Shoutcast Port, all future working well.
