### ISSUE TITLE
AAC Not Showing Up Working in 0.9.23

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/GlassCoder#5]
AAC and MPEG-4 HE-AAC+ not showing up as an optional Codec in GUI and Command Line

./configure output:
MPEG-4 HE-AAC+ (via FDKAAC) ... Yes  

[root@rd7-template glasscoder-0.9.23]# glasscoder --list-codecs
mp2
mp3
vorbis
pcm16
opus

**Comment by workino** [comment]
Confirmed also here.
compiled on raspbian and there is no possibility to select AAC codec.
Version: 0.10.0

**Comment by ElvishArtisan** [comment]
Almost certainly this is a path issue on Raspbian. ```glasscoder(1)``` looks for the codec DLLs in the standard library path (see the [dlopen(3) man page](https://linux.die.net/man/3/dlopen) for details), but fdk-aac installs thems them in '/usr/local/lib' by default, which is *not* on that path. Your options are:

- 1. Install the codec plug-ins in one of Raspian's standard library locations --e.g. by adding ```--libdir=/usr/lib``` to the 'configure' invocation when building fdk-aac. (Recommended)

- 2. Add the appropriate path to the ```LD_LIBRARY_PATH``` environmental variable when running ```glasscoder(1)```.

- 3. Add '/usr/local/lib' to Raspian's default library search path.

**Comment by workino** [comment]
Hello Fred,
i tried here is the screenshot :
![image](https://user-images.githubusercontent.com/2070098/72098360-97616780-331e-11ea-9433-f2fc762075ad.png)
but how u can see there is way glasscoder show up the coder :)
I compiled manually the fdk lib and glasscoder.
During the compilation glasscoder showed me the codec was present

Regards
Gabriele

**Comment by ElvishArtisan** [comment]
> During the compilation glasscoder showed me the codec was present

Which means that the fdk-aac headers were detected at build time. However, at runtime, ```dlopen()``` needs to be able to open the ```libfdk-aac``` DLL (on my setup, located at ```/usr/lib64/libfdk-aac.so.1```, which is a symlink to ```libfdk-aac.so.1.0.0```).

Where are these components on your setup? They should be in the same directory as ```libopus.so.0```.

**Comment by workino** [comment]
Can be Probably a problem with the newest library?
![image](https://user-images.githubusercontent.com/2070098/72099792-a0076d00-3321-11ea-9606-3f3c75994314.png)

This is the screen shot about all symbolic link i have .so.2.0.1 instead of .so.1.0.0

**Comment by workino** [comment]
Ok found. Is the codec version. Glasscoder is looking for .so.1 so i tried to create a symbolik link .so.1 pointing to so.2.0.1 and now in the list of codecs i have also accp 

Screen shot:

![image](https://user-images.githubusercontent.com/2070098/72100332-b82bbc00-3322-11ea-9999-a12ce4438bac.png)

![image](https://user-images.githubusercontent.com/2070098/72100343-bc57d980-3322-11ea-87c3-a25e4345bdae.png)

**Comment by ElvishArtisan** [comment]
> Ok found. Is the codec version. Glasscoder is looking for .so.1 so i tried to create a symbolik link .so.1 pointing to so.2.0.1 and now in the list of codecs i have also accp

Interesting! What version of fdk-aac are you using?

**Comment by workino** [comment]
> Interesting! What version of fdk-aac are you using?

I think is the latet 
libfdk-aac 2.0.1 manual compiled 

Regards
Gabriele

**Comment by ElvishArtisan** [comment]
Ah, I found it! Version skew problems. FDK-AAC bumped the DLL version to 2.0.1.

Fixed in 6a730a9. Please remove that symlink, then test with the updated version.

**Comment by workino** [comment]
Fred,
i can confirm now is working like a charm without the symbolic link :)
Is possible to close this issue

Great job
Gabriele

**Comment by ElvishArtisan** [comment]
Cool. Thank you!
