### ISSUE TITLE
OpenSSL incompatible with GPL - licence exception needed

### ISSUE THREAD

**Issue by paddatrapper** [ElvishArtisan/GlassCoder#8]
I would like to package GlassCoder for Debian, however this is currently blocked by licensing issues. OpenSSL has a licence that is incompatible with the GPL. It includes two additional clauses:

>  3. All advertising materials mentioning features or use of this 
>      software must display the following acknowledgment:
>      "This product includes software developed by the OpenSSL Project
>      for use in the OpenSSL Toolkit. (http://www.openssl.org/)"

>  6. Redistributions of any form whatsoever must retain the following 
>      acknowledgment:
>      "This product includes software developed by the OpenSSL Project
>      for use in the OpenSSL Toolkit (http://www.openssl.org/)"

Debian does not consider OpenSSL to be a system library, so requires an exception as described on the [GNU Foundation Website](https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs) for GPL software linking against OpenSSL to be packaged for Debian.

Please add such an exception so that I can package GlassCoder for Debian

**Comment by ElvishArtisan** [comment]
Added in 232eded.

**Comment by paddatrapper** [comment]
Thanks!
