### ISSUE TITLE
GlassCoder icecast v2 connection problem

### ISSUE THREAD

**Issue by newdanceradio** [ElvishArtisan/GlassCoder#9]
Hello Fred.
I'm trying to connect with glasscoder to icecast v2 server, but it doesn't connect.
In glassgui in Server Settings i'm choosing Icecast v2

![2020-02-03-122137_1920x1080_scrot](https://user-images.githubusercontent.com/17381301/73645343-c8179100-467f-11ea-9b7d-89f1d5824831.png)
then when i press Start button, in the log i see:

glasscoder: connection to "http://stream.newdanceradio.ru:80/mp3_192_fallback//mp3_192_fallback" lost

==============================================

I figured it out, glasscoder can connect to icecast server, but i should press many times  Start button and only then it could connect, i can't understand, why is it happening.

And, when glasscoder writes that it is Reconnecting... really it isn't reconnecting.
Is it possible to write in config file reconnecting time in seconds ?

**Comment by newdanceradio** [comment]
Hello Fred.

I figured it out, glasscoder can connect to icecast server, but i should press many times Start button and only then it could connect, i can't understand, why is it happening.

And, when glasscoder writes that it is Reconnecting... really it isn't reconnecting.
What could be the cause ?

![glasscoder](https://user-images.githubusercontent.com/17381301/80975598-f77a9d00-8e2a-11ea-87a5-9ee82b50089b.png)

**Comment by ElvishArtisan** [comment]
Should be fixed in 31807fa. Please test.

**Comment by newdanceradio** [comment]
> Should be fixed in [31807fa](https://github.com/ElvishArtisan/GlassCoder/commit/31807fa713715b91f84ecb781be8276678373f22). Please test.

Thank you Fred, and yes, now it works like a charm!

**Comment by ElvishArtisan** [comment]
Cool. Thank you for testing!
